### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by psychoticnmina** [luna-surf/website#1]
@nshout Can I help with whatever you're doing?

**Comment by seradotflac** [comment]
@CatPerson136 do I know you? This is sort of a private project.

**Comment by psychoticnmina** [comment]
Oh

**Comment by psychoticnmina** [comment]
> @CatPerson136 do I know you? This is sort of a private project.

I try to make a pull request for crazy editor

**Comment by Flixah** [comment]
> > @CatPerson136 do I know you? This is sort of a private project.
> 
> I try to make a pull request for crazy editor

so who r u?

**Comment by psychoticnmina** [comment]
> > > @CatPerson136 do I know you? This is sort of a private project.
> > 
> > I try to make a pull request for crazy editor
> 
> so who r u?

I'm a software developer that's willing to help

**Comment by Flixah** [comment]
> > > > @CatPerson136 do I know you? This is sort of a private project.
> > > 
> > > 
> > > I try to make a pull request for crazy editor
> > 
> > 
> > so who r u?
> 
> I'm a software developer that's willing to help

Sorry, we aren't currently looking for help on this project.
